logging:
  level:
    ROOT: INFO
    org:
      springframework:
        web: INFO
      hibernate: ERROR
  file: logs/application.log
  pattern:
    console: '%-5level %d{yyyy-MM-dd HH:mm:ss.SSS} %t %c{1} - %msg%n'
    file: '%-5level %d{yyyy-MM-dd HH:mm:ss.SSS} %t %c{1} - %msg%n'
spring:
  profiles:
    active: DEVELOPMENT